version: 1.0.{build}
os: Visual Studio 2017
configuration: Release
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
install:
- cmd: '"C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\sn.exe" -k External\Key.snk'
before_build:
- cmd: nuget restore
build:
  project: SimpleC.sln
  verbosity: minimal
test: off
artifacts:
- path: '**\*.vsix'
cache:
- packages -> **\packages.config
